### PR TITLE
Adding Consulting page designed from a template

### PR DESCRIPTION
**Pull request by fahadtejani**
https://github.com/goatandsheep/communote-tasks/issues/248

### CODE REVIEW

**Comment by fahadtejani** [comment]
@goatandsheep I can't add you as a reviewer since this is a draft pull request but feel free to check out the progress so far :)

**Comment by goatandsheep** [comment]
@fahadtejani not true 😛 I can review draft PRs

**Review by goatandsheep — CHANGES_REQUESTED** [review]
Why are they `.txt`?

**Comment by fahadtejani** [comment]
> Why are they `.txt`?

@goatandsheep My way of commenting out unnecessary pages/files, in case I want to use code blocks from other files. They will not be there for the actual pull request.

**Comment by goatandsheep** [comment]
Changing the file type messes with the git diff. I recommend you just put it in a separate folder or just leave them 😛

There are other options like putting it in a separate docs folder that isn't rendered and stuff, but don't push them as `.txt`

**Review by goatandsheep — APPROVED** [review]

**Pull request merged**
